### ISSUE TITLE
Extraction Error: 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by jaumeayats** [singer-io/tap-typeform#24]
Stitch reports the following error during an extraction from Typeform:

'NoneType' object is not iterable

The full extraction log is attached.
[144616.182664.sync.d196e1f4-83fd-11ea-a796-1292b2bce487.txt](https://github.com/singer-io/tap-typeform/files/4826438/144616.182664.sync.d196e1f4-83fd-11ea-a796-1292b2bce487.txt)

**Comment by fhinson** [comment]
I'm also experiencing this issue. @luandy64 is it possible you could take a look at this?

**Comment by aliw77** [comment]
+1 

Paste Log: https://pastebin.com/pyQDQBum

**Comment by Nicarim** [comment]
I'm facing same issue - what's the problem of just adding an IF condition to that script?

**Comment by giovanni-foorban** [comment]
+1

**Comment by Shanil6** [comment]
+1

**Comment by MuriloKakazu** [comment]
From reading your logs this does seem like the same problem I faced. It's now being fixed in https://github.com/singer-io/tap-typeform/pull/69

**Comment by kethan1122** [comment]
Closing this issue, since it was fixed in #69
