### ISSUE TITLE
Answers + Landings tables no longer refreshing

### ISSUE THREAD

**Issue by nmccormick-bombas** [singer-io/tap-typeform#25]
Has anyone seen an issue with answers + landings tables being stale? Only my questions table is updating, despite certainty that there have been new responses to the survey I'm pulling in.

**Comment by jackiegillis** [comment]
Hi @nmccormick-bombas did you ever find a resolution to this? I am experiencing the same thing.

**Comment by nmccormick-bombas** [comment]
Hey there!

No solution as of yet. One thing that will work - if you setup separate
integrations for your different taboola accounts. A bit of a PIA, but it
will prevent the pipe from breaking. The table only has issues landing when
you have a parent account to multiple taboola accounts.

**Comment by moseleyi** [comment]
I have noticed the same thing. I managed to get answers when I keep changing tables to replicate settings but now landings won't get updated

**Comment by aosen96** [comment]
I have the same issue. Managed to fix it back in December by changing the token in typeform and resetting the integration, and making it run the entire integration again. It took hours but seemed to work... until I just got back to work today and it's broken again. 

This has been an issue multiple times over the past couple of years and it's baffling to me that this never gets fixed.

**Comment by vivianngo97** [comment]
I am experiencing the same issue as well. It seems to be a frequent occurrence. Are there any fixes being done right now?

**Comment by phil-kramer** [comment]
Echoing this. My Answers and Landings tables just don't load.

<img width="1197" alt="Screen Shot 2021-04-04 at 12 00 38 PM" src="https://user-images.githubusercontent.com/76264363/113518800-87065f80-9556-11eb-9cd5-0f94244a4786.png">

**Comment by hespelz** [comment]
Having the same problem as well. Issue #28 has some more detail and advice for a workaround.
